version: '3.7'

x-network: &default-network
  vp:

x-logging: &default-logging
  driver: local
  options:
    max-size: 10m
    max-file: 3

services:
  db:
    image: vp_pg:local
    build:
      context: docker/db/
      args:
        - DATABASE_NAME
        - DATABASE_USER
        - DATABASE_PW
    volumes:
      - data_volume_pg:/var/lib/postgresql/data
    networks:
      <<: *default-network
    hostname: db
    # logging: *default-logging
    stop_grace_period: 30s

  django:
    image: vp_django:local
    build:
      context: ./
      args:
        - VP_BASE_DIR=${VP_BASE_DIR:-/opt/vp}
        - DEV=True
    command:
      - runserver
      - 0.0.0.0:8000
    volumes:
      - ./:/opt/vp
    networks:
      <<: *default-network
    ports:
      - "8000:8000"
    hostname: django
    links:
      - db
    # logging: *default-logging
    stop_grace_period: 10s

    environment:
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE-volunteer_planner.settings.local_postgres}
      DATABASE_ENGINE: ${DATABASE_ENGINE:-django.db.backends.postgresql}
      DATABASE_HOST: db
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PW: ${DATABASE_PW}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS:-localhost}
      SECRET_KEY: ${SECRET_KEY:?Please set djangos SECRET_KEY in .env or build environment}
      ADMIN_EMAIL: ${ADMIN_EMAIL:-admin@localhost}
      DJANGO_FROM_EMAIL: ${DJANGO_FROM_EMAIL:-admin@localhost}
      DJANGO_SERVER_EMAIL: ${DJANGO_SERVER_EMAIL:-admin@localhost}
      DJANGO_EMAIL_BACKEND: ${DJANGO_EMAIL_BACKEND:-django.core.mail.backends.console.EmailBackend}
      DJANGO_EMAIL_HOST:
      DJANGO_EMAIL_PORT:

volumes:
  data_volume_pg:

networks:
  <<: *default-network


# vim: ts=2:sts=2:sw=2:ai:et
